import type { Meta, StoryObj } from '@storybook/react';
import Alert from '../../components/Alert';
declare const meta: Meta<typeof Alert>;
export default meta;
type Story = StoryObj<typeof Alert>;
export declare const Default: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Gallery: Story;
