import type { Meta, StoryObj } from '@storybook/react';
import Badge from '../../elements/badge';
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof Badge>;
export declare const Default: Story;
export declare const Primary: Story;
export declare const WithAdditionalText: Story;
export declare const TruncatedText: Story;
export declare const WithTooltip: Story;
export declare const Gallery: Story;
