import type { Meta, StoryObj } from '@storybook/react';
import Button from '../../elements/button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Tertiary: Story;
export declare const CTA: Story;
export declare const Disabled: Story;
export declare const Loading: Story;
export declare const WithLeftIcon: Story;
export declare const WithRightIcon: Story;
export declare const WithTooltip: Story;
export declare const Gallery: Story;
