import type { Meta, StoryObj } from '@storybook/react';
import Input from '../../elements/input/Input';
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const WithIcon: Story;
export declare const WithInfo: Story;
export declare const ErrorState: Story;
export declare const Disabled: Story;
export declare const Password: Story;
