import type { Meta, StoryObj } from '@storybook/react';
import Stepper from '../../components/stepper/Stepper';
declare const meta: Meta<typeof Stepper>;
export default meta;
type Story = StoryObj<typeof Stepper>;
export declare const Default: Story;
export declare const FirstStep: Story;
export declare const CustomLineColor: Story;
export declare const CustomLabelVariant: Story;
export declare const Gallery: Story;
